// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoooHaX_uQk3rEu1wYjpoCP9RtTh-zhrA',
    appId: '1:645663670654:web:6b65d35111116bfc97f32f',
    messagingSenderId: '645663670654',
    projectId: 'fir-bookmark-83e5e',
    authDomain: 'fir-bookmark-83e5e.firebaseapp.com',
    storageBucket: 'fir-bookmark-83e5e.appspot.com',
    measurementId: 'G-XCDWTJ9WYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH_p9hfr-UxH7IZUYIF-4rV_NiQeXaCLQ',
    appId: '1:645663670654:android:b639f20ac90b8eb897f32f',
    messagingSenderId: '645663670654',
    projectId: 'fir-bookmark-83e5e',
    storageBucket: 'fir-bookmark-83e5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_sLw-aDTCUsU9Iv2svadMjUtbz9-xhM',
    appId: '1:645663670654:ios:940d643f04f6dbaf97f32f',
    messagingSenderId: '645663670654',
    projectId: 'fir-bookmark-83e5e',
    storageBucket: 'fir-bookmark-83e5e.appspot.com',
    iosBundleId: 'com.example.firebaseBookmark',
  );
}
